"""empty message

Revision ID: 047a26ec7eea
Revises: b166757881e9
Create Date: 2025-12-18 15:35:00.208058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '047a26ec7eea'
down_revision = 'b166757881e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userid', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_posts_userid_users', 'users', ['userid'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_users_email', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_email', type_='unique')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_posts_userid_users', type_='foreignkey')
        batch_op.drop_column('userid')

    # ### end Alembic commands ###
